// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsnkhnalhjtzahwnlyqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzbmtobmFsaGp0emFod25seXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNDgxMzQsImV4cCI6MjA3NDYyNDEzNH0.ybR6GUNUfeMiCpHuTKME7JXD2g4Js9jTQ8l4H-8a6m8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});